version: '2'

services:
  converter:
    build: ./app-crawler
    volumes:
      - ./app-crawler:/app-crawler
    user: root
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=127.0.0.1.nip.io
    command: ['gunicorn', '-c', 'config.py', 'app:app']
