version: '2'

services:
  app_store_crawler:
    build: ./app-crawler
    volumes:
      - ./app-crawler:/app-crawler
    user: root
    expose:
      - "5000"
    command: ['gunicorn', '-c', 'config.py', 'app:app']
